### ISSUE TITLE
Unable to load assets: assets.zip (No such file or directory)

### ISSUE THREAD

**Issue by handsetvn** [pedja1/SMC-Android#16]
java.lang.IllegalStateException: Unable to load assets: assets.zip (No such file or directory)
	at rs.pedjaapps.smc.assets.Assets.<init>(Assets.java:61)
	at rs.pedjaapps.smc.MaryoGame.create(MaryoGame.java:36)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.initializeListener(Lwjgl3Window.java:255)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:222)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:122)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:95)
	at rs.pedjaapps.smc.desktop.DesktopLauncher.main(DesktopLauncher.java:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Exception in thread "main" java.lang.NullPointerException
	at rs.pedjaapps.smc.MaryoGame.dispose(MaryoGame.java:62)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.dispose(Lwjgl3Window.java:264)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.cleanup(Lwjgl3Application.java:148)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:99)
	at rs.pedjaapps.smc.desktop.DesktopLauncher.main(DesktopLauncher.java:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
AL lib: (EE) alc_cleanup: 1 device not closed

Process finished with exit code 1

Can anyone help me ?

**Comment by djhamilton** [comment]
Unable to load assets: assets.zip (No such file or directory)

**Comment by pedja1** [comment]
You need to pack following folders in zip.
/data/data
/data/data_1080
/data/data_768
/data/data_540

Rename this file to "main.{versionCode}.rs.pedjaapps.smc.android.debug.obb" and put it in /sdcard/Android/obb/rs.pedjaapps.smc/android.debug folder on you android.

**Comment by handsetvn** [comment]
/usr/lib/jvm/jdk1.8.0_45/bin/java -Didea.launcher.port=7534 -Didea.launcher.bin.path=/home/longtran/working/tool/android-studio/bin -Dfile.encoding=UTF-8 -classpath /usr/lib/jvm/jdk1.8.0_45/jre/lib/charsets.jar:/usr/lib/jvm/jdk1.8.0_45/jre/lib/deploy.jar:/usr/lib/jvm/jdk1.8.0_45/jre/lib/ext/cldrdata.jar:/usr/lib/jvm/jdk1.8.0_45/jre/lib/ext/dnsns.jar:/usr/lib/jvm/jdk1.8.0_45/jre/lib/ext/jfxrt.jar:/usr/lib/jvm/jdk1.8.0_45/jre/lib/ext/localedata.jar:/usr/lib/jvm/jdk1.8.0_45/jre/lib/ext/nashorn.jar:/usr/lib/jvm/jdk1.8.0_45/jre/lib/ext/sunec.jar:/usr/lib/jvm/jdk1.8.0_45/jre/lib/ext/sunjce_provider.jar:/usr/lib/jvm/jdk1.8.0_45/jre/lib/ext/sunpkcs11.jar:/usr/lib/jvm/jdk1.8.0_45/jre/lib/ext/zipfs.jar:/usr/lib/jvm/jdk1.8.0_45/jre/lib/javaws.jar:/usr/lib/jvm/jdk1.8.0_45/jre/lib/jce.jar:/usr/lib/jvm/jdk1.8.0_45/jre/lib/jfr.jar:/usr/lib/jvm/jdk1.8.0_45/jre/lib/jfxswt.jar:/usr/lib/jvm/jdk1.8.0_45/jre/lib/jsse.jar:/usr/lib/jvm/jdk1.8.0_45/jre/lib/management-agent.jar:/usr/lib/jvm/jdk1.8.0_45/jre/lib/plugin.jar:/usr/lib/jvm/jdk1.8.0_45/jre/lib/resources.jar:/usr/lib/jvm/jdk1.8.0_45/jre/lib/rt.jar:/media/longtran/6D3A-73D6/working/game/git/SMC-Android/desktop/build/classes/main:/media/longtran/6D3A-73D6/working/game/git/SMC-Android/core/build/classes/main:/home/longtran/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx/1.9.2/e641cb91bec06bc64d9ddf7a7d7062caceec73cd/gdx-1.9.2.jar:/home/longtran/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-freetype/1.9.2/3609253d14edb1b3ca5aacff4e06989edde75be4/gdx-freetype-1.9.2.jar:/home/longtran/.gradle/caches/modules-2/files-2.1/org.json/json/20090211/c183aa3a2a6250293808bba12262c8920ce5a51c/json-20090211.jar:/media/longtran/6D3A-73D6/working/game/git/SMC-Android/core/build/libs/core-1.0.jar:/home/longtran/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-backend-lwjgl3/1.9.2/e80001b77396bf0f63df44721331588e55b8d2cf/gdx-backend-lwjgl3-1.9.2.jar:/home/longtran/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-tools/1.9.2/37d8e3009ae0febdf93717b21980c67c8cadac07/gdx-tools-1.9.2.jar:/home/longtran/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-platform/1.9.2/dde4cf7e9ce61c24042f512203aed87657496639/gdx-platform-1.9.2-natives-desktop.jar:/home/longtran/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-freetype-platform/1.9.2/1e1afb0b6c9e8aeb7d495cb8f55c353d3da58cf0/gdx-freetype-platform-1.9.2-natives-desktop.jar:/home/longtran/.gradle/caches/modules-2/files-2.1/org.slf4j/slf4j-log4j12/1.7.12/485f77901840cf4e8bf852f2abb9b723eb8ec29/slf4j-log4j12-1.7.12.jar:/home/longtran/.gradle/caches/modules-2/files-2.1/org.lwjgl/lwjgl/3.0.0b/e5753ecf8c2232243c4ddae0a901acf9cb7f5f57/lwjgl-3.0.0b.jar:/home/longtran/.gradle/caches/modules-2/files-2.1/org.lwjgl/lwjgl-platform/3.0.0b/a64481b1b5262bb74a66ebf88e82e6548194cf48/lwjgl-platform-3.0.0b-natives-windows.jar:/home/longtran/.gradle/caches/modules-2/files-2.1/org.lwjgl/lwjgl-platform/3.0.0b/b7d71d5bd83ac0c62fccf4b4fc82bcd94c0f887f/lwjgl-platform-3.0.0b-natives-linux.jar:/home/longtran/.gradle/caches/modules-2/files-2.1/org.lwjgl/lwjgl-platform/3.0.0b/b0c36452c9972f4027f1d9466280dfd5d0888e62/lwjgl-platform-3.0.0b-natives-osx.jar:/home/longtran/.gradle/caches/modules-2/files-2.1/com.badlogicgames.jlayer/jlayer/1.0.1-gdx/7cca83cec5c1b2f011362f4d85aabd71a73b049d/jlayer-1.0.1-gdx.jar:/home/longtran/.gradle/caches/modules-2/files-2.1/org.jcraft/jorbis/0.0.17/8872d22b293e8f5d7d56ff92be966e6dc28ebdc6/jorbis-0.0.17.jar:/home/longtran/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-backend-lwjgl/1.9.2/d710a8704ed584ec2ba9ca52e3a6a5885dd759cc/gdx-backend-lwjgl-1.9.2.jar:/home/longtran/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-backend-headless/1.9.2/813e6020de85cd831f02cb5e9060fd7ea8cb208e/gdx-backend-headless-1.9.2.jar:/home/longtran/.gradle/caches/modules-2/files-2.1/org.slf4j/slf4j-api/1.7.12/8e20852d05222dc286bf1c71d78d0531e177c317/slf4j-api-1.7.12.jar:/home/longtran/.gradle/caches/modules-2/files-2.1/log4j/log4j/1.2.17/5af35056b4d257e4b64b9e8069c0746e8b08629f/log4j-1.2.17.jar:/home/longtran/.gradle/caches/modules-2/files-2.1/org.lwjgl.lwjgl/lwjgl/2.9.2/a9d80fe5935c7a9149f6584d9777cfd471f65489/lwjgl-2.9.2.jar:/home/longtran/.gradle/caches/modules-2/files-2.1/org.lwjgl.lwjgl/lwjgl_util/2.9.2/4b9e37300a87799856e0bd15ed81663cdb6b0947/lwjgl_util-2.9.2.jar:/home/longtran/.gradle/caches/modules-2/files-2.1/org.lwjgl.lwjgl/lwjgl-platform/2.9.2/510c7d317f5e9e700b9cfaac5fd38bdebf0702e0/lwjgl-platform-2.9.2-natives-windows.jar:/home/longtran/.gradle/caches/modules-2/files-2.1/org.lwjgl.lwjgl/lwjgl-platform/2.9.2/d276cdf61fe2b516c7b7f4aa1b8dea91dbdc8d56/lwjgl-platform-2.9.2-natives-linux.jar:/home/longtran/.gradle/caches/modules-2/files-2.1/org.lwjgl.lwjgl/lwjgl-platform/2.9.2/d55b46b40b40249d627a83a7f7f22649709d70c3/lwjgl-platform-2.9.2-natives-osx.jar:/home/longtran/.gradle/caches/modules-2/files-2.1/net.java.jinput/jinput/2.0.5/39c7796b469a600f72380316f6b1f11db6c2c7c4/jinput-2.0.5.jar:/home/longtran/.gradle/caches/modules-2/files-2.1/net.java.jutils/jutils/1.0.0/e12fe1fda814bd348c1579329c86943d2cd3c6a6/jutils-1.0.0.jar:/home/longtran/.gradle/caches/modules-2/files-2.1/net.java.jinput/jinput-platform/2.0.5/7ff832a6eb9ab6a767f1ade2b548092d0fa64795/jinput-platform-2.0.5-natives-linux.jar:/home/longtran/.gradle/caches/modules-2/files-2.1/net.java.jinput/jinput-platform/2.0.5/385ee093e01f587f30ee1c8a2ee7d408fd732e16/jinput-platform-2.0.5-natives-windows.jar:/home/longtran/.gradle/caches/modules-2/files-2.1/net.java.jinput/jinput-platform/2.0.5/53f9c919f34d2ca9de8c51fc4e1e8282029a9232/jinput-platform-2.0.5-natives-osx.jar:/media/longtran/6D3A-73D6/working/game/git/SMC-Android/desktop/build/libs/desktop-1.0.jar:/home/longtran/working/tool/android-studio/lib/idea_rt.jar com.intellij.rt.execution.application.AppMain rs.pedjaapps.smc.desktop.DesktopLauncher
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
com.badlogic.gdx.utils.GdxRuntimeException: File not found: data/shaders/gs.vert (Internal)
	at com.badlogic.gdx.files.FileHandle.read(FileHandle.java:136)
	at com.badlogic.gdx.files.FileHandle.length(FileHandle.java:602)
	at com.badlogic.gdx.files.FileHandle.estimateLength(FileHandle.java:233)
	at com.badlogic.gdx.files.FileHandle.readString(FileHandle.java:198)
	at com.badlogic.gdx.files.FileHandle.readString(FileHandle.java:191)
	at com.badlogic.gdx.graphics.glutils.ShaderProgram.<init>(ShaderProgram.java:178)
	at rs.pedjaapps.smc.shader.Shader.init(Shader.java:20)
	at rs.pedjaapps.smc.MaryoGame.create(MaryoGame.java:37)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.initializeListener(Lwjgl3Window.java:255)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:222)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:122)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:95)
	at rs.pedjaapps.smc.desktop.DesktopLauncher.main(DesktopLauncher.java:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Exception in thread "main" java.lang.NullPointerException
	at java.util.Hashtable.put(Hashtable.java:459)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Preferences.putString(Lwjgl3Preferences.java:83)
	at rs.pedjaapps.smc.utility.PrefsManager.setSaveGame(PrefsManager.java:49)
	at rs.pedjaapps.smc.utility.GameSave.save(GameSave.java:45)
	at rs.pedjaapps.smc.utility.GameSave.dispose(GameSave.java:50)
	at rs.pedjaapps.smc.MaryoGame.dispose(MaryoGame.java:65)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.dispose(Lwjgl3Window.java:264)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.cleanup(Lwjgl3Application.java:148)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:99)
	at rs.pedjaapps.smc.desktop.DesktopLauncher.main(DesktopLauncher.java:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
AL lib: (EE) alc_cleanup: 1 device not closed

Process finished with exit code 1

**Comment by pedja1** [comment]
Working directory must be "android/assets".

**Comment by handsetvn** [comment]
![screenshot from 2016-05-04 21 42 45](https://cloud.githubusercontent.com/assets/2859031/15017835/78f560b4-1241-11e6-99aa-a119aaf7ac27.png)

![screenshot from 2016-05-04 21 46 02](https://cloud.githubusercontent.com/assets/2859031/15017889/a40d7fe8-1241-11e6-9bd7-36879f92a87c.png)

i have configure working directory back to assets folder, but the error still happens.

**Comment by handsetvn** [comment]
com.badlogic.gdx.utils.GdxRuntimeException: Couldn't load file: data/game/logo/libgdx.jpg
	at com.badlogic.gdx.graphics.Pixmap.<init>(Pixmap.java:148)
	at com.badlogic.gdx.graphics.TextureData$Factory.loadFromFile(TextureData.java:98)
	at com.badlogic.gdx.graphics.Texture.<init>(Texture.java:100)
	at com.badlogic.gdx.graphics.Texture.<init>(Texture.java:92)
	at rs.pedjaapps.smc.screen.SplashScreen.show(SplashScreen.java:47)
	at com.badlogic.gdx.Game.setScreen(Game.java:61)
	at rs.pedjaapps.smc.MaryoGame.create(MaryoGame.java:39)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.initializeListener(Lwjgl3Window.java:255)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:222)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:122)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:95)
	at rs.pedjaapps.smc.desktop.DesktopLauncher.main(DesktopLauncher.java:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: java.lang.NullPointerException: entry
	at java.util.zip.ZipFile.getInputStream(ZipFile.java:347)
	at rs.pedjaapps.smc.assets.ArchiveFileHandle.read(ArchiveFileHandle.java:69)
	at com.badlogic.gdx.files.FileHandle.readBytes(FileHandle.java:222)
	at com.badlogic.gdx.graphics.Pixmap.<init>(Pixmap.java:145)
	... 16 more

Process finished with exit code 0

**Comment by pedja1** [comment]
Zip file should contain data folder in root not in asset subfolder

**Comment by handsetvn** [comment]
![screenshot from 2016-05-04 22 00 50](https://cloud.githubusercontent.com/assets/2859031/15018457/cde9004c-1243-11e6-9ea5-0e5a4a2f5f44.png)


com.badlogic.gdx.utils.GdxRuntimeException: Couldn't load file: data/game/logo/libgdx.jpg
	at com.badlogic.gdx.graphics.Pixmap.<init>(Pixmap.java:148)
	at com.badlogic.gdx.graphics.TextureData$Factory.loadFromFile(TextureData.java:98)
	at com.badlogic.gdx.graphics.Texture.<init>(Texture.java:100)
	at com.badlogic.gdx.graphics.Texture.<init>(Texture.java:92)
	at rs.pedjaapps.smc.screen.SplashScreen.show(SplashScreen.java:47)
	at com.badlogic.gdx.Game.setScreen(Game.java:61)
	at rs.pedjaapps.smc.MaryoGame.create(MaryoGame.java:39)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.initializeListener(Lwjgl3Window.java:255)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:222)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:122)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:95)
	at rs.pedjaapps.smc.desktop.DesktopLauncher.main(DesktopLauncher.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: com.badlogic.gdx.utils.GdxRuntimeException: File not found in archive: data/game/logo/libgdx.jpg
	at rs.pedjaapps.smc.assets.ArchiveFileHandle.read(ArchiveFileHandle.java:69)
	at com.badlogic.gdx.files.FileHandle.readBytes(FileHandle.java:222)
	at com.badlogic.gdx.graphics.Pixmap.<init>(Pixmap.java:145)
	... 16 more

Process finished with exit code 0

**Comment by pedja1** [comment]
No, not like that
Folder structure in zip should be like this

assets.zip
  - data/
  - data_1080/
  - data_768/
  - data_540

![screenshot from 2016-05-04 17 11 43](https://cloud.githubusercontent.com/assets/1208796/15018811/96d0e0ca-121b-11e6-95e7-ae82633ba206.png)

**Comment by handsetvn** [comment]
it has worked smoothly, but i still have got error notifications:

com.badlogic.gdx.utils.GdxRuntimeException: com.badlogic.gdx.utils.GdxRuntimeException: File not found in archive: data/animation/particles/box_activated.p
	at com.badlogic.gdx.assets.AssetManager.handleTaskError(AssetManager.java:570)
	at com.badlogic.gdx.assets.AssetManager.update(AssetManager.java:375)
	at rs.pedjaapps.smc.screen.LoadingScreen.render(LoadingScreen.java:84)
	at com.badlogic.gdx.Game.render(Game.java:46)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:235)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:122)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:95)
	at rs.pedjaapps.smc.desktop.DesktopLauncher.main(DesktopLauncher.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: com.badlogic.gdx.utils.GdxRuntimeException: File not found in archive: data/animation/particles/box_activated.p
	at rs.pedjaapps.smc.assets.ArchiveFileHandle.read(ArchiveFileHandle.java:69)
	at com.badlogic.gdx.graphics.g2d.ParticleEffect.loadEmitters(ParticleEffect.java:151)
	at com.badlogic.gdx.graphics.g2d.ParticleEffect.load(ParticleEffect.java:137)
	at com.badlogic.gdx.assets.loaders.ParticleEffectLoader.load(ParticleEffectLoader.java:41)
	at com.badlogic.gdx.assets.loaders.ParticleEffectLoader.load(ParticleEffectLoader.java:30)
	at com.badlogic.gdx.assets.AssetLoadingTask.handleSyncLoader(AssetLoadingTask.java:101)
	at com.badlogic.gdx.assets.AssetLoadingTask.update(AssetLoadingTask.java:88)
	at com.badlogic.gdx.assets.AssetManager.updateTask(AssetManager.java:498)
	at com.badlogic.gdx.assets.AssetManager.update(AssetManager.java:373)
	... 11 more

Process finished with exit code 0

**Comment by pedja1** [comment]
If you look at the source, file is there. Check if you have checked out latest commit, and recreate zip

**Comment by handsetvn** [comment]
I got it, thanks.
